export const JIRA_WIKI_SAMPLE = [
  "h2. Expected Behavior",
  "",
  "Desk staff manage pantry items with a name, a restock date, an active flag, and the usual audit fields.",
  "",
  "MOCK UI: [^pantry-items-prototype.html]",
  "",
  "h2. Acceptance Criteria",
  "",
  "URL: [https://example.com/pantry/items]",
  "* UI supports: create, update, delete, and review pantry item records.",
  "* UI supports: download the pantry list to Excel.",
  "* UI supports: bulk upload to add, update, and delete records (per defined template and validation rules).",
  "* Search/filter by: Item Name, Active Flag, Restock From, Restock To.",
  "* Role/permission model matches the existing pantry desk (confirm with the owner if a new role is needed).",
  "",
  "h2. Validation",
  "",
  "* Create/update/review: pantry item records can be managed end-to-end in the desk UI.",
  "* Excel download matches the grid and the current filter. Bulk upload succeeds for add, update, and delete, and shows validation errors in the form.",
  "* Search filters return the expected subset for Item Name, Active Flag, Restock From, and Restock To.",
  "",
  "h3. Open Questions",
  "",
  "-pending UI mockup and review the implementation detail-",
  "",
  "how to manage the user permissions?",
  "",
  "From the desk owner:",
  "",
  "_A separate edit role is better. Only a few people should change records, so a viewer in another site does not edit them by accident._",
  "",
  "|Role|Role Owner Approval?|Permission|",
  "|PantryItemEdit|YES|Creation Delete Modification|",
  "|PantryItemView|YES|Read Only|",
  "",
  "Put the desk owner down as the approver.",
].join("\n");
